/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibuatincv.pengguna;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Acer
 */
public class formulir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formulir.class.getName());

    /**
     * Creates new form login
     */
    public formulir() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    int pilihan = javax.swing.JOptionPane.showConfirmDialog(
                    null, 
                    "Formulir kamu belum tersimpan, yakin mau keluar?",
                    "Konfirmasi Keluar",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE);
                
                if(pilihan == javax.swing.JOptionPane.YES_OPTION){
                    System.exit(0);
                } 
            }
        });
        
        generate.setEnabled(false); // Membuat tombol jadi abu-abu di awal
        setPlaceholder(nama, "Nama");
        setPlaceholder(alamat, "Alamat tidak perlu lengkap: Kecamatan Kabupaten Provinsi");
        setPlaceholder(noHP, "No telepon yang dapat dihubungi.");
        setPlaceholder(email, "Email aktif yang dapat dihubungi.");
        setPlaceholder(edukasi, "");
        setPlaceholder(tentangsaya, "");
        setPlaceholder(pengalaman, ""); 
        setPlaceholder(projek, "");
        setPlaceholder(kepemimpinan, "");
        setPlaceholder(skill, "");
//        setPlaceholder(nosim, "Nomor SIM Aktif");

        javax.swing.event.DocumentListener listenerForm = new javax.swing.event.DocumentListener() {
        @Override public void insertUpdate(javax.swing.event.DocumentEvent e) { cekKondisiFormulir(); // Dipicu saat user mengetik karakter baru
        }
        @Override public void removeUpdate(javax.swing.event.DocumentEvent e) { cekKondisiFormulir(); // Dipicu saat user menghapus karakter
        }
        @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { cekKondisiFormulir(); // Dipicu jika ada perubahan gaya teks (jarang terjadi pada plain text)
        }
    };

    
        
//    listenerForm();   // Memanggil fungsi detektor ketikan
        // Daftarkan listener ke dokumen milik masing-masing field input Anda
    nama.getDocument().addDocumentListener(listenerForm);
    alamat.getDocument().addDocumentListener(listenerForm);
    noHP.getDocument().addDocumentListener(listenerForm);
    email.getDocument().addDocumentListener(listenerForm);
    edukasi.getDocument().addDocumentListener(listenerForm);
    tentangsaya.getDocument().addDocumentListener(listenerForm);
    pengalaman.getDocument().addDocumentListener(listenerForm);
    projek.getDocument().addDocumentListener(listenerForm);
    kepemimpinan.getDocument().addDocumentListener(listenerForm);
    skill.getDocument().addDocumentListener(listenerForm);
//    nosim.getDocument().addDocumentListener(listenerForm);
        
        
        generate.setEnabled(false); //matiin tombol generate biar ga tiba" nyimpen
        this.setLocationRelativeTo(null);  //ini biar ditengah yaw
    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        noHP = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        edukasi = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        tentangsaya = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        pengalaman = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        projek = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        kepemimpinan = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        skill = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dibuatin.CV");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(700, 1000));

        jLabel3.setText("Formulir Data Diri");

        nama.addActionListener(this::namaActionPerformed);

        alamat.addActionListener(this::alamatActionPerformed);

        noHP.addActionListener(this::noHPActionPerformed);

        edukasi.setColumns(20);
        edukasi.setRows(5);
        jScrollPane6.setViewportView(edukasi);

        tentangsaya.setColumns(20);
        tentangsaya.setRows(5);
        jScrollPane13.setViewportView(tentangsaya);

        pengalaman.setColumns(20);
        pengalaman.setRows(5);
        jScrollPane8.setViewportView(pengalaman);

        projek.setColumns(20);
        projek.setRows(5);
        jScrollPane14.setViewportView(projek);

        kepemimpinan.setColumns(20);
        kepemimpinan.setRows(5);
        jScrollPane10.setViewportView(kepemimpinan);

        skill.setColumns(20);
        skill.setRows(5);
        jScrollPane11.setViewportView(skill);

        jLabel2.setText("Tuliskan pendidikan terakhir saja, cukup enter saja format yang diberi nomor");

        jLabel4.setText("1. Nama Universitas. 2. Nama Fakultas/jurusan. 3. Gelar akademik. 4. IPK/Nilai Rapot. 5. Bulan & tahun kelulusan");

        jLabel5.setText("Isikan tentang kamu, buat dengan format paragraf");

        jLabel6.setText("Pengalaman kerja berkesan dan sesuai yang kamu lamar. Keahlian riset dan latar belakang akademis.");

        jLabel7.setText("Proyek spesifik yang pernah dikerjakan. Alat/software yang dikuasai.");

        jLabel8.setText("Tuliskan pengalamanmu sesuai dengan posisi yang ingin kmau tunjukkan.");

        jLabel9.setText("!!Awali bagian yang ingin di point dengan FULL KAPITAL!! ●Jenis Pengalaman.");

        jLabel10.setText("-Nama tempat. -Lokasi | Bulan, Tahun Mulai – Bulan, Tahun Selesai. -Poin tanggung jawab/pencapaian utama.");

        jLabel11.setText("Isi dengan projek yang sudah pernah kamu buat baik itu individu maupun tim.");

        jLabel12.setText("!!Awali bagian yang ingin di point dengan FULL KAPITAL!! ●Nama Kompetisi/Proyek");

        jLabel13.setText("-Instansi/Kelas | Bulan, Tahun. -Prestasi yang dicapai. -Detail teknis pengerjaan/metodologi yang digunakan.");

        jLabel14.setText("Tuliskan pengalaman kepemimpinan kamu !!Awali bagian yang ingin di point dengan FULL KAPITAL!!");

        jLabel15.setText("●Jabatan. -Organisasi | Bulan, Tahun Mulai – Sekarang/Selesai");

        jLabel16.setText("-Tanggung jawab atau peran strategis dalam organisasi. -Kontribusi nyata bagi anggota atau organisasi.");

        jLabel17.setText("Isi kemampuan/bakat kamu, terutama hard skill yaa");

        jLabel18.setText("[Contoh]Computer: [Software/Bahasa pemrograman yang dikuasai]");

        jLabel19.setText("[Contoh]Bahasa: [Bahasa yang dikuasai].");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );

        jScrollPane1.setViewportView(jPanel5);

        generate.setText("Submit");
        generate.addActionListener(this::generateActionPerformed);

        kembali.setText("Kembali");
        kembali.addActionListener(this::kembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 352, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(kembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generate)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(kembali))
                .addGap(512, 512, 512))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
          // 1. Ambil data dari form
          // 1. Ambil data dari form
    String Nama         = nama.getText().trim();
    String Alamat       = alamat.getText().trim();
    String NoHp         = noHP.getText().trim();
    String Email        = email.getText().trim();
    String Edukasi      = edukasi.getText().trim();       // ✅ edukasi → pendidikan
    String TentangSaya  = tentangsaya.getText().trim();   // ✅ tentangsaya → tentang_saya
    String Pengalaman   = pengalaman.getText().trim();    // ✅ pengalaman → pengalaman
    String Projek       = projek.getText().trim();        // ✅ projek → projek
    String Kepemimpinan = kepemimpinan.getText().trim();  // ✅ kepemimpinan → kepemimpinan
    String Skill        = skill.getText().trim();         // ✅ skill → keahlian
//    String Nosim        = nosim.getText().trim();

    SessionManager session = SessionManager.getInstance();
    int idUser = session.getIdUser();
    String namaDesain = session.getNamaDesain();

    try {
        java.sql.Connection conn = com.mycompany.dibuatincv.DBConnection.getKoneksi();

        String sqlData = "INSERT INTO data_diri "
            + "(id_user, nama, alamat, no_wa, email, pendidikan, tentang_saya, keahlian, pengalaman, kepemimpinan, projek, pilihan_desain, baca, generate)"
            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
            
        java.sql.PreparedStatement psData = conn.prepareStatement(
            sqlData, java.sql.Statement.RETURN_GENERATED_KEYS
        );
        
        psData.setInt(1, idUser);
        psData.setString(2, Nama);
        psData.setString(3, Alamat);
        psData.setString(4, NoHp);
        psData.setString(5, Email);
        psData.setString(6, Edukasi);       // ✅ pendidikan
        psData.setString(7, TentangSaya);   // ✅ tentang_saya
        psData.setString(8, Skill);         // ✅ keahlian
        psData.setString(9, Pengalaman);    // ✅ pengalaman
        psData.setString(10, Kepemimpinan); // ✅ kepemimpinan
        psData.setString(11, Projek);       // ✅ projek
        psData.setString(12, namaDesain);
        psData.setBoolean(13, false);
        psData.setBoolean(14, false);
//        psData.setString(15, Nosim);

        psData.executeUpdate();

        java.sql.ResultSet rsData = psData.getGeneratedKeys();
        if (rsData.next()) {
            int idData = rsData.getInt(1);
            session.setIdData(idData);
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

        proses prosesCV = new proses();
        prosesCV.setVisible(true);
        this.dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_generateActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        halamanUtama formulir = new halamanUtama();
        formulir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void noHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHPActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new formulir().setVisible(true);
                }
                        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea edukasi;
    private javax.swing.JTextField email;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton kembali;
    private javax.swing.JTextArea kepemimpinan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField noHP;
    private javax.swing.JTextArea pengalaman;
    private javax.swing.JTextArea projek;
    private javax.swing.JTextArea skill;
    private javax.swing.JTextArea tentangsaya;
    // End of variables declaration//GEN-END:variables

//   fungsi membuat teks bayangan
    // Fungsi placeholder untuk JTextField (Kolom Nama)
    private void setPlaceholder(JTextField textfield, String hint) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    textfield.setText(hint);
    textfield.setForeground(java.awt.Color.GRAY);
    textfield.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (textfield.getText().equals(hint)) {
                textfield.setText("");
                textfield.setForeground(java.awt.Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (textfield.getText().trim().isEmpty()) {
                textfield.setText(hint);
                textfield.setForeground(java.awt.Color.GRAY);
            }
        }
    });
    }
    private void setPlaceholder(javax.swing.JTextArea textArea, String hint) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    textArea.setText(hint);
    textArea.setForeground(java.awt.Color.GRAY);
    textArea.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (textArea.getText().equals(hint)) {
                textArea.setText("");
                textArea.setForeground(java.awt.Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (textArea.getText().trim().isEmpty()) {
                textArea.setText(hint);
                textArea.setForeground(java.awt.Color.GRAY);
            }
            cekKondisiFormulir(); // Setiap kali kursor keluar, cek status tombol
        }
    });
    }
    
    // Fungsi untuk memverifikasi apakah semua kolom sudah terisi
private void cekKondisiFormulir() {
    String Nama = nama.getText().trim();
    String Alamat = alamat.getText().trim();
    String Nohp = noHP.getText().trim();
    String Email = email.getText().trim();
    String Edukasi = edukasi.getText().trim();
    String Tentangsaya = tentangsaya.getText().trim();
    String Pengalaman = pengalaman.getText().trim();
    String Projek = projek.getText().trim();
    String Kepemimpinan = kepemimpinan.getText().trim();
    String Skill = skill.getText().trim();
//    String Nosim = nosim.getText().trim();
    
    // Definisikan teks petunjuk yang sama persis
    String hintNama = "Nama";
    String hintAlamat = "Alamat tidak perlu lengkap\nKecamatan\nKabupaten\nProvinsi";
    String hintNohp = "No telepon yang dapat dihubungi.";
    String hintEmail = "Email aktif yang dapat dihubungi.";
    String hintEdukasi = "";
    String hintTentangsaya = "";
    String hintPengalaman = "";
    String hintProjek = "";
    String hintKepemimpinan = "";
    String hintSkill = "";
//    String hintNosim = "Nomor SIM Aktif";
        

    // Validasi ketat: dianggap valid jika tidak kosong DAN bukan merupakan teks petunjuk
    boolean isNamaValid = !Nama.isEmpty() && !Nama.equals(hintNama);
    boolean isAlamatValid = !Alamat.isEmpty() && !Alamat.equals(hintAlamat);
    boolean isNohpValid = !Nohp.isEmpty() && !Nohp.equals(hintNohp);
    boolean isEmailValid = !Email.isEmpty() && !Email.equals(hintEmail);
    boolean isEdukasiValid = !Edukasi.isEmpty() && !Edukasi.equals(hintEdukasi);
    boolean isTentangsayaValid = !Tentangsaya.isEmpty() && !Tentangsaya.equals(hintTentangsaya);
    boolean isPengalamanValid = !Pengalaman.isEmpty() && !Pengalaman.equals(hintPengalaman);
    boolean isProjekValid = !Projek.isEmpty() && !Projek.equals(hintProjek);
    boolean isKepemimpinanValid = !Kepemimpinan.isEmpty() && !Kepemimpinan.equals(hintKepemimpinan);
    boolean isSkillValid = !Skill.isEmpty() && !Skill.equals(hintSkill);
//    boolean isNosimValid = !Nosim.isEmpty() && !Nosim.equals(hintNosim);

    // Tombol aktif hanya jika semua form valid
    boolean semuaTerisi = isNamaValid && isAlamatValid && isNohpValid && isEmailValid && isEdukasiValid && isTentangsayaValid && isPengalamanValid && isProjekValid && isKepemimpinanValid && isSkillValid 
//            && isNosimValid
            ;
    generate.setEnabled(semuaTerisi);
      // 4. Jika semua form terisi dengan data asli user, tombol baru menyala aktif
    if (isNamaValid && isAlamatValid && isNohpValid && isEmailValid && isEdukasiValid && isTentangsayaValid && isPengalamanValid && isProjekValid && isKepemimpinanValid && isSkillValid 
//            && isNosimValid
            ) {
        generate.setEnabled(true);
    } else {
        generate.setEnabled(false); // Tetap abu-abu
    }
} }
