/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibuatincv.pengguna;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class proses extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(proses.class.getName());

    /**
     * Creates new form login
     */
    public proses() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        ImageIcon gifIcon = new ImageIcon("src/main/java/com/mycompany/dibuatincv/images/centang.gif");
        pink.setIcon(gifIcon);
        
//buat mastiin user jangan keluar sistem pls pls pls
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                
//ini pop-up konfirmasi ya atau tidak
                int pilihan = javax.swing.JOptionPane.showConfirmDialog(
                null, 
                "Proses sedang berjalan. Apakah Anda yakin ingin meninggalkan aplikasi?", 
                "Konfirmasi Keluar", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
                );
//ya ini user fiks keluar
            if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
                System.exit(0); // Aplikasi ditutup paksa sepenuhnya
                }
            }
            
        });
        
        javax.swing.Timer timer = new javax.swing.Timer(5000, null);
    timer.addActionListener(e -> {
    try {
        int idData = SessionManager.getInstance().getIdData();
        
        // ✅ Pakai koneksi BARU setiap cek agar data selalu fresh
        java.sql.Connection conn = com.mycompany.dibuatincv.DBConnection.getKoneksiBaru();
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "SELECT path_cv FROM data_diri WHERE id_data = ?"
        );
        ps.setInt(1, idData);
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            int statusGen = rs.getInt("generate");
            System.out.println("Status generate: " + statusGen); // DEBUG
            
            if (statusGen == 1) {
                timer.stop();
                rs.close(); ps.close(); conn.close();
                
                javax.swing.SwingUtilities.invokeLater(() -> {
                    finalResult hasil = new finalResult();
                    hasil.setVisible(true);
                    com.mycompany.dibuatincv.pengguna.proses.this.dispose();
                });
            } else {
                rs.close(); ps.close(); conn.close();
            }
        }
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
});
    timer.start(); // ← mulai cek otomatis
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pink = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dibuatin.CV");

        pink.setAutoscrolls(true);

        jLabel2.setText("CV kamu sedang diproses, mohon jangan tekan tombol tutup(close) selama masa pemrosesan berlangsung. kamu bisa tekan tombol minimize sajaa<3");

        jButton1.setText("Refresh");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(pink, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(pink, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cekStatusCV();
    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public class gifViewer {
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new proses().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pink;
    // End of variables declaration//GEN-END:variables
private void cekStatusCV() {
    try {
        int idData = SessionManager.getInstance().getIdData();
        System.out.println("Cek idData: " + idData); // DEBUG
        
        java.sql.Connection conn = com.mycompany.dibuatincv.DBConnection.getKoneksiBaru();
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "SELECT generate FROM data_diri WHERE id_data = ?"
        );
        ps.setInt(1, idData);
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            int statusGen = rs.getInt("generate");
            System.out.println("Status generate: " + statusGen); // DEBUG
            
            if (statusGen == 1) {
                // CV sudah selesai → pindah ke finalResult
                rs.close(); ps.close(); conn.close();
                finalResult hasil = new finalResult();
                hasil.setVisible(true);
                this.dispose();
                return;
            }
        }
        rs.close(); ps.close(); conn.close();
        
        // Belum selesai → kasih tahu user
        javax.swing.JOptionPane.showMessageDialog(this,
            "CV kamu masih diproses oleh admin.\nKlik OK, tunggu sekitar 3 menit, lalu tekan tombol 'Refresh' lagi ya!",
            "Masih Diproses",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }}
}

