/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibuatincv.konsultan;

import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class review extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(review.class.getName());
    private int idDataTerpilih;
    /**
     * Creates new form review
     */
    public review() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public review(int id) {
    this.idDataTerpilih = id;
    initComponents();  // pack() dipanggil di sini
    pack();            // pastikan komponen sudah punya ukuran
    loadDataCV();      // baru load setelah ukuran tersedia
}

    private void loadDataCV() {
    try {
        java.sql.Connection conn = com.mycompany.dibuatincv.DBConnection.getKoneksi();
        
        // Mengambil kolom path_cv dan nama untuk memuat dokumen visual
        String sql = "SELECT nama, path_cv FROM data_diri WHERE id_data = ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, this.idDataTerpilih);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String namaFileCV = rs.getString("path_cv");
            
            if (namaFileCV != null && !namaFileCV.isEmpty()) {
                // Lokasi folder tempat aplikasi kamu menyimpan hasil generate gambar CV
                // Sesuaikan "src/output_cv/" dengan lokasi folder penyimpanan asli di project-mu
                String pathLengkap = System.getProperty("user.home") + "/Documents/" + namaFileCV; 
                
                java.io.File fileGambar = new java.io.File(pathLengkap);
                if (fileGambar.exists()) {
    if (namaFileCV.endsWith(".pdf")) {
        // Render halaman pertama PDF jadi gambar
        org.apache.pdfbox.pdmodel.PDDocument doc = 
            org.apache.pdfbox.pdmodel.PDDocument.load(new java.io.File(pathLengkap));
        
        org.apache.pdfbox.rendering.PDFRenderer renderer = 
            new org.apache.pdfbox.rendering.PDFRenderer(doc);
        
        java.awt.image.BufferedImage bim = renderer.renderImageWithDPI(0, 150);
        doc.close();
        
        int targetW = lbl_gambar_cv.getWidth() > 0 ? lbl_gambar_cv.getWidth() : 314;
        int targetH = lbl_gambar_cv.getHeight() > 0 ? lbl_gambar_cv.getHeight() : 410;
        
        java.awt.Image imgSkala = bim.getScaledInstance(targetW, targetH, java.awt.Image.SCALE_SMOOTH);
        lbl_gambar_cv.setIcon(new javax.swing.ImageIcon(imgSkala));
        
    } else {
        // File gambar biasa (PNG, JPG, dll)
        javax.swing.ImageIcon iconAwal = new javax.swing.ImageIcon(pathLengkap);
        
        int targetW = lbl_gambar_cv.getWidth() > 0 ? lbl_gambar_cv.getWidth() : 314;
        int targetH = lbl_gambar_cv.getHeight() > 0 ? lbl_gambar_cv.getHeight() : 410;
        
        java.awt.Image imgSkala = iconAwal.getImage().getScaledInstance(
            targetW, targetH, java.awt.Image.SCALE_SMOOTH
        );
        lbl_gambar_cv.setIcon(new javax.swing.ImageIcon(imgSkala));
    }
} else {
    lbl_gambar_cv.setText("File gambar CV tidak ditemukan di folder.");
}
            } else {
                lbl_gambar_cv.setText("CV Pengguna belum di-generate oleh sistem.");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat visual CV: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRevisi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_gambar_cv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRevisi.setBackground(new java.awt.Color(255, 204, 204));

        text_note.setColumns(20);
        text_note.setRows(5);
        jScrollPane1.setViewportView(text_note);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel1.setText("Note");

        btn_send.setText("Kirim Admin");
        btn_send.addActionListener(this::btn_sendActionPerformed);

        btn_back.setText("Kembali");
        btn_back.addActionListener(this::btn_backActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 35)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dibuatin.CV");

        javax.swing.GroupLayout PanelRevisiLayout = new javax.swing.GroupLayout(PanelRevisi);
        PanelRevisi.setLayout(PanelRevisiLayout);
        PanelRevisiLayout.setHorizontalGroup(
            PanelRevisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRevisiLayout.createSequentialGroup()
                .addGroup(PanelRevisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelRevisiLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRevisiLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbl_gambar_cv, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRevisiLayout.createSequentialGroup()
                .addGap(127, 959, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(270, 270, 270))
            .addGroup(PanelRevisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRevisiLayout.setVerticalGroup(
            PanelRevisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRevisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRevisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_gambar_cv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(PanelRevisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRevisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRevisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
String catatan = text_note.getText();
    
    try {
        java.sql.Connection conn = com.mycompany.dibuatincv.DBConnection.getKoneksi();
        
        // UPDATE langsung menuju kolom note_revisi
        String sql = "UPDATE data_diri SET note_revisi = ?, generate = 2 WHERE id_data = ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, catatan);
        ps.setInt(2, this.idDataTerpilih);
        
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Catatan revisi berhasil dikirim ke Admin!");
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengirim catatan: " + e.getMessage());
    }
    konsultan review = new konsultan();
    review.setVisible(true);
    dispose();
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        try {
            // Membuka kembali halaman utama konsultan
            konsultan halamanUtama = new konsultan(); 
            halamanUtama.setLocationRelativeTo(null);
            halamanUtama.setVisible(true);
            
            // Menutup halaman revisi saat ini agar tidak menumpuk
            this.dispose(); 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal kembali: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new review().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRevisi;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_gambar_cv;
    private javax.swing.JTextArea text_note;
    // End of variables declaration//GEN-END:variables
}
