/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibuatincv;

//import com.mycompany.dibuatincvnw.konsultan.konsultan;
import com.mycompany.dibuatincv.admin.DashboardAdmin;
import com.mycompany.dibuatincv.konsultan.konsultan;
import com.mycompany.dibuatincv.pengguna.SessionManager;
import com.mycompany.dibuatincv.pengguna.halamanUtama;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class formotp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formotp.class.getName());

    
     private  String username;
    private  String nomor;
    private  String hakAkses;
    private  String otpSistem;
 
public formotp(String username, String nomor, String hakAkses, String otpSistem) {
    initComponents();
    this.username = username;
    this.nomor = nomor;
    this.hakAkses = hakAkses;
    this.otpSistem = otpSistem;
}

    public formotp() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

// Atau mengatur ukuran berdasarkan layar pengguna
//java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
//this.setSize(screenSize.width * 80 / 100, screenSize.height * 80 / 100); // 80% dari ukuran layar
//this.setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kode_otp = new javax.swing.JTextField();
        btn_otp = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 50)); // NOI18N
        jLabel1.setText("KODE OTP");

        kode_otp.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        kode_otp.setForeground(new java.awt.Color(153, 153, 153));
        kode_otp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kode_otp.addActionListener(this::kode_otpActionPerformed);

        btn_otp.setText("Verifikasi");
        btn_otp.addActionListener(this::btn_otpActionPerformed);

        back.setText("kembali");
        back.addActionListener(this::backActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 35)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dibuatin.CV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(215, 215, 215)
                                .addComponent(btn_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kode_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(kode_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_otpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_otpActionPerformed

    private void btn_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_otpActionPerformed
String otpInputUser = kode_otp.getText().trim();

    // 1. Validasi OTP
    if (!otpInputUser.equals(otpSistem)) {
        JOptionPane.showMessageDialog(null, "Kode OTP Salah!");
        return;
    }

    // 2. LOGIKA PENGAMANAN KETAT
    try {
        // --- CEK ADMIN ---
        if (username.equalsIgnoreCase("Fidya") && nomor.equals("085802516802")) {
            if (hakAkses.equalsIgnoreCase("admin")) {
                new DashboardAdmin().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login Gagal: Admin harus memilih hak akses Admin!");
            }
        } 
        // --- CEK KONSULTAN ---
        else if (username.equalsIgnoreCase("Shely") && nomor.equals("081913363720")) {
            if (hakAkses.equalsIgnoreCase("konsultan")) {
                new konsultan().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login Gagal: Konsultan harus memilih hak akses Konsultan!");
            }
        }
        // --- CEK PENGGUNA (DATABASE) ---
        else if (hakAkses.equalsIgnoreCase("pengguna")) {
    java.sql.Connection conn = DBConnection.getKoneksi();
    String sqlCek = "SELECT * FROM user WHERE nama = ?";
    java.sql.PreparedStatement psCek = conn.prepareStatement(sqlCek);
    psCek.setString(1, username);
    java.sql.ResultSet rs = psCek.executeQuery();
    
    if (rs.next()) {
        // ✅ TAMBAHAN: Simpan id_user ke session
        int idUser = rs.getInt("id_user");
        SessionManager.getInstance().setIdUser(idUser);
        SessionManager.getInstance().setUsername(username);
        
        // Update nomor WA jika user sudah ada
        String sqlUpdate = "UPDATE user SET no_wa = ? WHERE nama = ?";
        java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
        psUpdate.setString(1, nomor);
        psUpdate.setString(2, username);
        psUpdate.executeUpdate();
        
    } else {
        // Insert jika user baru
        String sqlInsert = "INSERT INTO user (nama, no_wa, hak_akses) VALUES (?, ?, ?)";
        java.sql.PreparedStatement psInsert = conn.prepareStatement(
            sqlInsert, java.sql.Statement.RETURN_GENERATED_KEYS // ✅ TAMBAHAN
        );
        psInsert.setString(1, username);
        psInsert.setString(2, nomor);
        psInsert.setString(3, "pengguna");
        psInsert.executeUpdate();
        
        // ✅ TAMBAHAN: Ambil id_user yang baru dibuat
        java.sql.ResultSet rsInsert = psInsert.getGeneratedKeys();
        if (rsInsert.next()) {
            int idUser = rsInsert.getInt(1);
            SessionManager.getInstance().setIdUser(idUser);
            SessionManager.getInstance().setUsername(username);
        }
    }
    
    JOptionPane.showMessageDialog(null, "Login Berhasil!");
    new halamanUtama().setVisible(true);
    dispose();
        }} catch (SQLException ex) {
            System.getLogger(formotp.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
// String otpInputUser = kode_otp.getText().trim();
//
//    // 1. Validasi OTP
//    if (!otpInputUser.equals(otpSistem)) {
//        JOptionPane.showMessageDialog(null, "Kode OTP Salah!");
//        return;
//    }
//
//    // 2. LOGIKA PENGAMANAN KETAT
//    try {
//        // --- CEK ADMIN ---
//        if (username.equalsIgnoreCase("Fidya") && nomor.equals("085802516802")) {
//            if (hakAkses.equalsIgnoreCase("admin")) {
//                //new admin().setVisible(true);
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Login Gagal: Admin harus memilih hak akses Admin!");
//            }
//        } 
//        // --- CEK KONSULTAN ---
//        else if (username.equalsIgnoreCase("Bu Anin") && nomor.equals("6288215626763")) {
//            if (hakAkses.equalsIgnoreCase("konsultan")) {
////                new konsultan().setVisible(true);
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Login Gagal: Konsultan harus memilih hak akses Konsultan!");
//            }
//        }
//        // --- CEK PENGGUNA (DATABASE) ---
//        else if (hakAkses.equalsIgnoreCase("pengguna")) {
//            java.sql.Connection conn = DBConnection.getKoneksi();
//            String sqlCek = "SELECT * FROM user WHERE nama = ?";
//            java.sql.PreparedStatement psCek = conn.prepareStatement(sqlCek);
//            psCek.setString(1, username);
//            java.sql.ResultSet rs = psCek.executeQuery();
//            
//            if (rs.next()) {
//                // Update nomor WA jika user sudah ada
//                String sqlUpdate = "UPDATE user SET no_wa = ? WHERE nama = ?";
//                java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
//                psUpdate.setString(1, nomor);
//                psUpdate.setString(2, username);
//                psUpdate.executeUpdate();
//            } else {
//                // Insert jika user baru
//                String sqlInsert = "INSERT INTO user (nama, no_wa, hak_akses) VALUES (?, ?, ?)";
//                java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
//                psInsert.setString(1, username);
//                psInsert.setString(2, nomor);
//                psInsert.setString(3, "pengguna");
//                psInsert.executeUpdate();
//            }
//            
//            JOptionPane.showMessageDialog(null, "Login Berhasil!");
//            new halamanUtama().setVisible(true);
//            dispose();
//        } 
//        else {
//            JOptionPane.showMessageDialog(null, "Akses ditolak: Hak akses tidak valid!");
//        }
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Database: " + e.getMessage());
//        e.printStackTrace();
//    }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_otpActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        login salah = new login();
        salah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formotp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btn_otp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kode_otp;
    // End of variables declaration//GEN-END:variables
}
