/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibuatincv;

import javax.swing.JFrame;
import javax.swing.*;
//import jakarta.servlet.http.HttpSession;

/**
 *
 * @author Acer
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        // Membuat jendela terbuka secara maksimal (Maximize)
this.setExtendedState(JFrame.MAXIMIZED_BOTH);

// Atau mengatur ukuran berdasarkan layar pengguna
//java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
//this.setSize(screenSize.width * 80 / 100, screenSize.height * 80 / 100); // 80% dari ukuran layar
//this.setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        input_nama = new javax.swing.JTextField();
        no_wa = new javax.swing.JTextField();
        akses = new javax.swing.JComboBox<>();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DibuatinCV");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(328, 328, 328))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 45)); // NOI18N
        jLabel3.setText("Login");

        input_nama.setBackground(new java.awt.Color(255, 204, 204));
        input_nama.setForeground(new java.awt.Color(153, 153, 153));
        input_nama.setText("Nama");
        input_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_namaFocusLost(evt);
            }
        });
        input_nama.addActionListener(this::input_namaActionPerformed);

        no_wa.setBackground(new java.awt.Color(255, 204, 204));
        no_wa.setForeground(new java.awt.Color(153, 153, 153));
        no_wa.setText("Nomor Whatsapp");
        no_wa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                no_waFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                no_waFocusLost(evt);
            }
        });

        akses.setBackground(new java.awt.Color(255, 204, 204));
        akses.setForeground(new java.awt.Color(102, 102, 102));
        akses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pengguna", "Admin", "Konsultan" }));

        btn_login.setBackground(new java.awt.Color(255, 204, 204));
        btn_login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(this::btn_loginActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akses, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_wa, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addComponent(jLabel3))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(no_wa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akses, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_namaActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    String username = input_nama.getText().trim();
    String nomor = no_wa.getText().trim(); 
    String hakAksesPilihan = akses.getSelectedItem().toString();
        
    if(username.isEmpty() || nomor.isEmpty()){
        JOptionPane.showMessageDialog(null, "Username dan Nomor WA tidak boleh kosong!");
        return;
    }

    int randomOtp = (int)(Math.random() * 900000) + 100000 ;
    String generatedOtp = String.valueOf(randomOtp);

    String tokenFonnte = "gEirsvwnBtHWrNxE1EUs"; 
    String isiPesan = "KODE OTP LOGIN ANDA: " + generatedOtp + "\nJangan berikan kode ini kepada siapapun.";

    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                java.net.URL url = new java.net.URL("https://api.fonnte.com/send");
                java.net.HttpURLConnection con = (java.net.HttpURLConnection) url.openConnection();
                con.setRequestMethod("POST");
                con.setDoOutput(true);
                con.setRequestProperty("Authorization", tokenFonnte);
                
                String payload = "target=" + nomor + "&message=" + java.net.URLEncoder.encode(isiPesan, "UTF-8");
                
                try (java.io.OutputStream os = con.getOutputStream()) {
                    byte[] input = payload.getBytes("utf-8");
                    os.write(input, 0, input.length);			
                }
                
                int responseCode = con.getResponseCode();
                
                if (responseCode == java.net.HttpURLConnection.HTTP_OK) {
    javax.swing.SwingUtilities.invokeLater(() -> {
        JOptionPane.showMessageDialog(null, "Kode OTP berhasil dikirim ke WhatsApp!");
        formotp halamanOtp = new formotp(username, nomor, hakAksesPilihan, generatedOtp);
        halamanOtp.setVisible(true);
        dispose(); 
    });
} else {
                    java.io.BufferedReader br = new java.io.BufferedReader(new java.io.InputStreamReader(con.getErrorStream()));
                    String line;
                    StringBuilder response = new StringBuilder();
                    while ((line = br.readLine()) != null) {
                        response.append(line);
                    }
                    JOptionPane.showMessageDialog(null, "Fonnte Menolak! Code: " + responseCode + "\nAlasan: " + response.toString());
                }
                con.disconnect();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Kesalahan Jaringan: " + e.getMessage());
            }
        }
    }).start();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void input_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_namaFocusGained
        // TODO add your handling code here:
        if (input_nama.getText().equals("Nama")) {
        input_nama.setText("");
    }
    }//GEN-LAST:event_input_namaFocusGained

    private void input_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_namaFocusLost
        // TODO add your handling code here:
        if (input_nama.getText().isEmpty()) {
        input_nama.setText("Nama");
    }
    }//GEN-LAST:event_input_namaFocusLost

    private void no_waFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_no_waFocusGained
        // TODO add your handling code here:
        if(no_wa.getText().equals("Nomor Whatsapp")){
        no_wa.setText("");
        }
    }//GEN-LAST:event_no_waFocusGained

    private void no_waFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_no_waFocusLost
        // TODO add your handling code here:
        if(no_wa.getText().isEmpty()){
        no_wa.setText("Nomor Whatsapp");}
    }//GEN-LAST:event_no_waFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }
     private String input_akses() {
        String hasilAkses = akses.getSelectedItem().toString(); 
    return hasilAkses;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akses;
    private javax.swing.JButton btn_login;
    private javax.swing.JTextField input_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField no_wa;
    // End of variables declaration//GEN-END:variables
}
